name: flutterapp
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  video_player: ^2.7.0
  chewie: ^1.11.3
  google_maps_flutter: ^2.3.0
  geolocator: ^9.0.2

flutter:
  uses-material-design: true