name: flutterapp
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  video_player: ^2.7.0
  chewie: ^0.9.10

flutter:
  uses-material-design: true