server:
    port: 8082
    context-path: /client2
    session:
      cookie:
        name: UISESSION
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: SampleClientId
      clientSecret: secret
      accessTokenUri: http://localhost:8080/auth-server/oauth/token
      userAuthorizationUri: http://localhost:8080/auth-server/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/auth-server/org/me
spring:
  thymeleaf:
    cache: false        