spring:
  # ?????
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.106:3306/xj_doc?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ENC(BLC3UQBxshlcA9tnMyJL7w==)

# ????
jasypt:
  encryptor:
    # ????????????????????
    password: 0f7b0a5d-46bc-40fd-b8ed-3181d21d644f
    # ????????????????????
    algorithm: PBEWithMD5AndDES

    iv-generator-classname: org.jasypt.iv.NoIvGenerator

#    property:
#      # ???????????ENC()??????????????????????
#      prefix: ENC@[
#      suffix: ]
