# 配置到 Docker 中
global:
  # 设置抓取数据的时间间隔，间隔设置为每15秒一次。默认为每1分钟。
  scrape_interval:     15s
  # 设定抓取数据的超时时间，默认为10s
  scrape_timeout: 15s
  # 设置规则刷新，每15秒刷新一次规则。默认值为每1分钟。
  evaluation_interval: 15s

# 普罗米修斯与抓取模块交互的接口配置
scrape_configs:
  # 一定要全局唯一, 采集 Prometheus 自身的 metrics
  - job_name: 'study-spring-boot-metrics'
    # metrics_path defaults to '/metrics'
    metrics_path: '/actuator/prometheus'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['127.0.0.1:8080']
