apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: study
  name: study
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: study
    spec:
      containers:
        - image: bage2014/study
          name: study
          resources: {}
status: {}